# Generated by Django 4.2.7 on 2023-12-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='client_other_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
