# Generated by Django 5.0.2 on 2024-02-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='endTime',
        ),
    ]
