# Generated by Django 4.2.7 on 2023-12-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_service_client_other_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_other_email',
        ),
    ]
