# Generated by Django 4.2.7 on 2023-12-11 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
