# Generated by Django 4.2.7 on 2023-12-01 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_email_customuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('tax_residency', models.CharField(max_length=255)),
                ('tin', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('passport_id_number', models.CharField(max_length=50)),
                ('country_of_issue', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('client_contact_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(max_length=254)),
                ('preferred_language', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
