# Generated by Django 5.0.2 on 2024-02-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_reservation_endtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='endTime',
        ),
    ]
