# Generated by Django 4.2.7 on 2023-12-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_service_client_other_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='user',
            new_name='user_id',
        ),
    ]
