# Generated by Django 4.2.7 on 2023-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_customuser_registered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='registered_by',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
