# Generated by Django 4.2.7 on 2023-12-11 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_customuser_registered_by_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
