# Generated by Django 5.0.2 on 2024-02-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_reservation_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
