# Generated by Django 4.2.7 on 2023-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
