# Generated by Django 4.2.7 on 2023-12-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_service_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_id',
        ),
    ]
