# Generated by Django 4.2.7 on 2023-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_action_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='total_elapsed_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
