# Generated by Django 5.0.2 on 2024-03-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_customuser_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='registrarFirstName',
            new_name='registrarName',
        ),
    ]
