# Generated by Django 4.2.7 on 2023-12-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_useractionlog_granted_by_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Location',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='FullName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='UserType',
            new_name='UserRoles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='LastName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
