# Generated by Django 4.2.7 on 2023-12-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_location_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accessLevel',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
