# Generated by Django 4.2.7 on 2023-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_registrationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='user',
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
