# Generated by Django 5.0.2 on 2024-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_customuser_registrarname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registrarID',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
