# Generated by Django 4.2.7 on 2023-12-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_customuser_accesslevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
