# Generated by Django 4.2.7 on 2023-12-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_service_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='client_id',
        ),
    ]
