# Generated by Django 5.0.2 on 2024-03-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_customuser_registrarid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registrarID',
            field=models.CharField(max_length=25),
        ),
    ]
