# Generated by Django 5.0.2 on 2024-03-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_customuser_registrarid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accessLevel',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
    ]
