# Generated by Django 4.2.7 on 2023-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_service_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviced_client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
