# Generated by Django 4.2.7 on 2023-12-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_customuser_address_alter_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
