# Generated by Django 4.2.7 on 2023-12-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_customuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='LastName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
