# Generated by Django 5.0.2 on 2024-03-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_customuser_accesslevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
