# Generated by Django 4.2.7 on 2023-12-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_customuser_lastname_alter_customuser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='BirthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
