# Generated by Django 4.2.7 on 2023-12-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
