# Generated by Django 5.0.2 on 2024-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_customuser_nationalid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registrarEmail',
            field=models.EmailField(default=100, max_length=254),
            preserve_default=False,
        ),
    ]
