# Generated by Django 4.2.7 on 2023-12-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_customuser_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='full_name',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='tax_residency',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_contact_phone',
            new_name='clientContactPhone',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_email',
            new_name='clientEmail',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='country_of_issue',
            new_name='countryOfIssue',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='expiry_date',
            new_name='expiryDate',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='passport_id_number',
            new_name='passportIdNumber',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='place_of_birth',
            new_name='placeOfBirth',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='preferred_language',
            new_name='preferredLanguage',
        ),
        migrations.AddField(
            model_name='client',
            name='taxResidency',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
