# Generated by Django 4.2.7 on 2023-12-27 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_service_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deactivationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registrationDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 9, 53, 59, 740818, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='activationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activatorEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activatorFirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activatorID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deactivationDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deactivatorEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deactivatorFirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deactivatorID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registrationDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 9, 54, 20, 722265, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='resetDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 9, 54, 39, 954496, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='initationDate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 9, 54, 53, 33298, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
