# Generated by Django 5.0.2 on 2024-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_client_registraremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registrarEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='registrarID',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
