# Generated by Django 4.2.7 on 2023-12-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rename_full_name_client_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='isStaff',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='registered_by_fullname',
            new_name='registerarFirstName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='registered_by_id',
            new_name='registrarID',
        ),
    ]
