# Generated by Django 4.2.7 on 2023-12-27 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_client_activationdate_client_deactivationdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start',
        ),
    ]
