# Generated by Django 4.2.7 on 2023-12-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_end_time_event_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientRole_InCompany',
            new_name='contactPersonName',
        ),
        migrations.AddField(
            model_name='client',
            name='contactPersonEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contactPersonPhone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='introducerEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='introducerName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sharePercent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
