# Generated by Django 4.2.7 on 2023-12-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_rename_is_active_customuser_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activatorEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='activatorFirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='activatorID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='isActive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registerarFirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registrarEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registrarID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
