# Generated by Django 4.2.7 on 2023-12-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_client_activatoremail_client_activatorfirstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registrarEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
