# Generated by Django 4.2.7 on 2023-12-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rename_clientrole_incompany_client_contactpersonname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='dateOfBirth',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='expiryDate',
            new_name='passportExpiryDate',
        ),
    ]
