# Generated by Django 4.2.7 on 2023-12-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_client_registraremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='registerarFirstName',
            new_name='registrarFirstName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='registerarFirstName',
            new_name='registrarFirstName',
        ),
    ]
