# Generated by Django 5.0.2 on 2024-03-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_customuser_registrarid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
