# Generated by Django 4.2.7 on 2024-01-03 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_dateofbirth_client_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_taken', models.BooleanField(default=False)),
                ('schedule_date', models.DateTimeField()),
                ('set_date', models.DateTimeField(auto_now_add=True)),
                ('action_taken_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField()),
                ('scheduler_name', models.CharField(blank=True, max_length=255)),
                ('scheduler_email', models.EmailField(blank=True, max_length=254)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('setter_name', models.CharField(blank=True, max_length=255)),
                ('setter_email', models.EmailField(blank=True, max_length=254)),
                ('action_taker_name', models.CharField(blank=True, max_length=255)),
                ('action_taker_email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
