# Generated by Django 4.2.7 on 2023-12-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rename_registerarfirstname_client_registrarfirstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deactivatorEmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deactivatorFirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deactivatorID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='countryOfIssue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
