# Generated by Django 4.2.7 on 2024-01-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_alert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
