# Generated by Django 4.2.7 on 2023-12-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_client_deactivatoremail_client_deactivatorfirstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activatorEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='deactivatorEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
