# Generated by Django 5.0.2 on 2024-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='national_id_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registrationCertificate_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registrationCertificate_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tinNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
