# Generated by Django 4.2.7 on 2024-01-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alert_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='action_taken_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
