# Generated by Django 4.2.7 on 2023-12-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_client_activatoremail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RemoveField(
            model_name='client',
            name='occupation',
        ),
        migrations.AddField(
            model_name='client',
            name='clientRole_InCompany',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='currentAddress',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
