# Generated by Django 5.0.2 on 2024-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_client_national_id_link_client_passport_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='taxResidency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
