# Generated by Django 4.2.7 on 2023-12-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_rename_firstname_client_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientContactPhone',
            new_name='clientContact',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='tin',
            new_name='tinNumber',
        ),
        migrations.RemoveField(
            model_name='client',
            name='placeOfBirth',
        ),
        migrations.AlterField(
            model_name='client',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
