# Generated by Django 4.2.7 on 2024-01-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alert_action_taken_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
