# Generated by Django 4.2.7 on 2024-01-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alert_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_processed',
        ),
    ]
