# Generated by Django 4.2.7 on 2023-12-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_rename_clientcontactphone_client_clientcontact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Service',
        ),
    ]
