# Generated by Django 5.0.2 on 2024-04-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0023_customuser_taxresidency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passportIdNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customci_user_set', to='auth.group'),
        ),
    ]
