# Generated by Django 5.0.2 on 2024-04-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_customuser_citizenship_customuser_passportidnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferredLanguage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
