# Generated by Django 4.2.7 on 2024-01-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='FirstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
