# Generated by Django 5.0.2 on 2024-04-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_client_passportidnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='registrationCertificate_link',
            new_name='registration_certificate_link',
        ),
        migrations.AddField(
            model_name='customuser',
            name='countryOfResidence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='NationalID',
            field=models.CharField(blank=True, max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='UserRoles',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
