# Generated by Django 5.0.2 on 2024-04-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_rename_registrationcertificate_link_client_registration_certificate_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='NationalID',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='NationalID',
            field=models.CharField(max_length=35),
        ),
    ]
