# Generated by Django 5.0.2 on 2024-04-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_client_nationalid_alter_customuser_nationalid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='registrationCertificate_link',
            new_name='registration_certificate_link',
        ),
    ]
