# Generated by Django 4.2.7 on 2024-01-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_alter_useractionlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isStaff',
        ),
    ]
