# Generated by Django 4.2.7 on 2024-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_remove_customuser_isstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_datetime', models.DateTimeField()),
                ('day_of_week', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('FREE', 'Available'), ('BOOKED', 'Booked')], default='FREE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_contact', models.CharField(max_length=15)),
                ('service_title', models.CharField(max_length=255)),
                ('appointment_datetime', models.DateTimeField()),
            ],
        ),
    ]
