# Generated by Django 4.2.7 on 2024-01-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_options_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
