# Generated by Django 5.0.2 on 2024-04-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_client_modeofpayment_client_proposednameoption1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='financialForecast',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
