# Generated by Django 4.2.7 on 2024-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_options_status_alter_reservation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contract_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cv_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
