# Generated by Django 4.2.7 on 2024-01-30 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_customuser_contract_file_customuser_cv_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='contract_file',
            new_name='contract_link',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='cv_file',
            new_name='cv_link',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='passport_file',
            new_name='passport_link',
        ),
    ]
