# Generated by Django 5.0.2 on 2024-05-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0038_alter_client_citizenship_alter_client_clientcontact_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="uncompletedclient",
            name="NationalID",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uncompletedclient",
            name="passportIdNumber",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
