# Generated by Django 5.0.2 on 2024-05-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0039_alter_uncompletedclient_nationalid_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="client", name="passportExpiryDate",),
        migrations.AlterField(
            model_name="client",
            name="NationalID",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="passportIdNumber",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
