# Generated by Django 4.2.13 on 2024-06-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0046_alert_reminder_email_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="last_reminder_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
