# Generated by Django 4.2.13 on 2024-06-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0047_alert_last_reminder_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="client_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
