# Generated by Django 4.2.13 on 2024-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0048_alter_alert_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="client_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="scheduler_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
