# Generated by Django 4.2.13 on 2024-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0049_alter_alert_client_email_alter_alert_scheduler_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="client_reportee_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="reports",
            name="client_reportee_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reports",
            name="client_reportee_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
