# Generated by Django 4.2.13 on 2024-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0051_alter_reports_report_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="last_updated_by_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="reports",
            name="last_updated_by_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reports",
            name="last_updated_by_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
