# Generated by Django 4.2.13 on 2024-06-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0052_reports_last_updated_by_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reports",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="reports",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
