# Generated by Django 4.2.13 on 2024-07-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0053_alter_reports_description_alter_reports_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="sharesNumber",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="sharesType",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="statedCapital",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
