# Generated by Django 4.2.13 on 2024-07-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0054_client_sharesnumber_client_sharestype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uncompletedclient",
            name="sharesNumber",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="uncompletedclient",
            name="sharesType",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="uncompletedclient",
            name="statedCapital",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
