# Generated by Django 4.2.13 on 2024-09-17 23:23

import uuid
from django.db import migrations

def generate_random_tin(apps, schema_editor):
    Client = apps.get_model('backend', 'Client')
    
    # Get clients where tinNumber is null or empty
    clients_with_empty_tin = Client.objects.filter(tinNumber__isnull=True) | Client.objects.filter(tinNumber='')
    
    # Assign random UUID strings as tinNumber
    for client in clients_with_empty_tin:
        client.tinNumber = str(uuid.uuid4())  # Generate a random unique value
        client.save()

class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0055_uncompletedclient_sharesnumber_and_more"),
    ]

    operations = [
        migrations.RunPython(generate_random_tin),
    ]
