# Generated by Django 4.2.13 on 2024-09-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0057_alter_client_clientemail_alter_client_tinnumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="tinNumber",
            field=models.CharField(default=22, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
