# Generated by Django 4.2.13 on 2024-12-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0058_alter_client_tinnumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="contract_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cv_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="national_id_link",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
