# Generated by Django 4.2.13 on 2024-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0059_alter_customuser_contract_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="other_docs_link",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
