# Generated by Django 4.2.13 on 2024-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0060_customuser_other_docs_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="bankStatement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="bank_statement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="bank_statement_proceeds_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="bank_statements_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="bank_statements_proceeds_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="business_plan_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="cdd_documents_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="certificate_of_incumbency_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="certificate_of_registration_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="charter_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="confirmationLetter_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="creditor_agreement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="creditor_bank_statement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="creditor_cdd_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="custody_accounts_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="cv_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="declaration_of_trust_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="deed_of_retirement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="documentary_evidence_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="donor_bank_statement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="donor_source_of_wealth_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="due_diligence_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="executor_letter_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="financial_statements_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="funds_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="insurance_pay_out_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="latest_accounts_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="latest_accounts_or_bank_statements_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="lease_agreement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="legal_document_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="letter_from_donor_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="letter_from_relevant_org_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="licence_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="loan_agreement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="loan_bank_statement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="lottery_bank_statement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="national_id_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="notarised_documents_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="notary_letter_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="passport_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="payslips_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="principals_foundation_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="principals_identification_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="professionalReference_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="proof_of_ownership_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="proof_of_source_of_funds_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="proof_of_source_of_wealth_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="property_contract_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="register_of_trustee_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="registered_office_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="registration_certificate_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="related_third_party_bank_statement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="related_third_party_cdd_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="related_third_party_loan_agreement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="retirement_annuity_fund_statement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="shareholders_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="signature_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="signed_letter_from_notary_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="source_of_funds_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="source_of_wealth_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="unrelated_third_party_bank_statement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="unrelated_third_party_cdd_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="unrelated_third_party_loan_agreement_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="utility_link",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="wealth_link",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
