# Generated by Django 4.2.13 on 2024-12-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0061_alter_client_bankstatement_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uncompletedclient",
            name="other_necessary_documents_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
