# Generated by Django 4.2.13 on 2024-12-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0063_client_other_necessary_documents_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="other_necessary_documents_link",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
